### ISSUE TITLE
Comprar tarjeta micro SD para rPI 2

### ISSUE THREAD

**Issue by sebasgm** [cdrfiuba/reck#4]
Para poder empezar a utilizar la Raspberry PI 2 necesitamos una micro SD

**Comment by Monty1991** [comment]
Tengo una Sandisk de 32 gb sin usar, sirve?

**Comment by sebasgm** [comment]
Sirve hasta que podamos comprar una. Si querés traela y ni bien tengamos una nueva te la podés llevar.

**Comment by Monty1991** [comment]
Dale. ¿Cuándo empiezan a reunirse (en el club, supongo)?

**Comment by yagui** [comment]
Juli ya compró la SD
