### ISSUE TITLE
Sistema de tracción

### ISSUE THREAD

**Issue by ernestmc** [cdrfiuba/reck#7]
Me parece que el sistema de orugas va a ser difícil de implementar, especialmente el armado de las orugas. Propongo hacer un sistema con tracción en las cuatro ruedas: dos de un lado y dos del otro:

![traccion](https://cloud.githubusercontent.com/assets/9289769/13307777/a17a131c-db4c-11e5-92af-721af8005b39.png)

Se pueden usar piñones, coronas y cadenas de bicicleta o moto. Por ejemplo este kit de moto que se consigue en [Mercadolibre](http://articulo.mercadolibre.com.ar/MLA-607233544-kit-transmision-motos-110-corona-cadena-pinon-sti-motos-_JM):

![transmision_moto](https://cloud.githubusercontent.com/assets/9289769/13307813/fc3cbb2e-db4c-11e5-800e-84afed535528.jpg)

**Comment by yagui** [comment]
la cinta o cadena debería tener 2 metros de perímetro aproximadamente, para un robot de 75-80 cm de largo

**Comment by yagui** [comment]
Con la idea de Ernest, decidimos armar algo como lo que proponen acá
http://www.instructables.com/id/How-to-make-custom-and-strong-tank-tracks-for-very/

Las cadenas cuestan alrededor de 100 pesos cada una (ML), y hay una herramienta para cortar cadenas y volver a unirlas, con lo cual se pueden comprar varias cadenas para armar todas las orugas. La herramienta cuesta 150 pesos pero quizás se consiga mas barata en ML.
Una cadena de 2 metros necesitaría de 1 cadena y media comercial. Es decir, comprando 3 hacemos 2 para el robot.
Los piñones cuestan también entre 50 y 100 pesos (ML). Hay que comprar del mismo paso que la cadena.

*Queda definir si usamos 2 o 3 cadenas para cada oruga (4 o 6 en total, es decir 8 o 12 metros).
*Queda definir las maderas que usaríamos para armar la oruga.
*Queda definir cuantos piñones usamos por oruga.

**Comment by yagui** [comment]
Vamos a comprar 6 cadenas
http://articulo.mercadolibre.com.ar/MLA-623311125-cadena-para-bicicleta-kmc-hv410-marron-_JM
y uno de estos para armar las cadenas
http://articulo.mercadolibre.com.ar/MLA-628260843-corta-cadena-basico-marca-bike-hand-326a-_JM

Los eslabones son de 1/2 pulgada, y cada soporte va separado cada 2 pulgadas.

En total habrá 40 maderas por oruga, dando un total de 80 pulgadas o sea, 2,03 metros de orugas.

80 tablitas de 35 x 200 x 9 mm

**Comment by yagui** [comment]
compramos las cadenas.
